user_provided_paths << "https://hoganre.sharepoint.com/sites/UrtonLane"
user_provided_paths << "https://hoganre.sharepoint.com/sites/1317 Woodland Drive, Elizabethtown, KY" ; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/1701 N. Dixie"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/2101_N_Dixie"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/41 Shops North"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/41NSHO-SALE"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/4310 Bishop Lane"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/5911 Bardstown Road"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/6448 West Hwy 146"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/8717WestportRd"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/9420 Seatonville PetSuites"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Sale-ALEPLA"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/ORLYALE_SALE"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Alexandria"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/BARLOT_SALE"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Bardstown-Hwy245"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/UNILOT_SALE"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/BROPLA"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Cane Run & Terry"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Cane Run Terry Multifamily"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Cold_Spring"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Crestwood-Hwy329"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/DevelopmentProject"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Sale-DORCOM"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/1502NDixie"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Statrlite Starbucks"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Etown-I65_Mulberry"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/SBUX29090_SALE"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Ferdinand_IN"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Henderson-Audubon"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/HOGANREALESTATE3"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/HOGANREALESTATE14"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/HOGANREALESTATE49"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/HOGANREALESTATE92"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/HOGANREALESTATE74"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/HRE_Acquisitions"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/HRE Team Website"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Team Website(2)"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/HRE_Mgmt"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/350 West Court Ave"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Kroger Campbellsville"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Etowndollartree"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/loans"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Lou Taylorsville_Tucker"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/2601BardstownRd"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Master"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Murfreesboro"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/5426_Scottsville_Rd"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/LyndonLane"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/ORLYCrestwood"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/ORLYElizabethtown"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/ORLY-Lou-Blankenbaker"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/3207PrestonHwy"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/GrantlineRd"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/ORLYTaylorsville"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/100&104_West_Lewis&Clark"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/O'Rellys-100&104 Lewis&Clark"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/AllSalesTeam-c036c9b0-d80c-423b-afed-8642ce2d6076"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Hoover, AL PetSuites"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/PrincetonSC"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Project007"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/PA"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/SBX29090NEWPMAGMT"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Shelbyville"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/SBX27627"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Shepherdsville_Sale"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Starlite"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/TEST"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Gateway-Jeffersonville"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/TRIAL PAGE"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/Veterans"; sleep(2.seconds)
user_provided_paths << "https://hoganre.sharepoint.com/sites/VissingSale"; sleep(2.seconds)
